version: '3'
services:
  app:
    build:
      context: ./      
      dockerfile: Dockerfile    
    container_name: backend_api
    networks:
      - backendapi
    volumes: 
      - $PWD:$PWD
      - ~/.ssh:/root/.ssh
  server:
    container_name: NODEJS_SERVER_MEDIUM
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '5150:5150'

  db:
    image: 'mongo'
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

networks:
  backendapi:
    driver: bridge